/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Consolas', 'monospace'],
        display: ['Inter', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
      },
      borderRadius: {
        card: '10px',
        btn: '6px',
        pill: '9999px',
      },
      colors: {
        bg: 'var(--bg)',
        surface: 'var(--surface)',
        surface2: 'var(--surface-2)',
        'surface-1': 'var(--surface-1)',
        'surface-2': 'var(--surface-2)',
        'surface-3': 'var(--surface-3)',
        border: 'var(--border)',
        'border-subtle': 'var(--border-subtle)',
        'border-strong': 'var(--border-strong)',
        text: 'var(--text)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted': 'var(--text-muted)',
        muted: 'var(--muted)',
        accent: 'var(--accent)',
        accent2: 'var(--accent-2)',
        up: 'var(--up)',
        down: 'var(--down)',
        warn: 'var(--warn)',
        'warn-bg': 'var(--warn-bg)',
        bull: 'var(--bull)',
        'bull-bg': 'var(--bull-bg)',
        'bull-text': 'var(--bull-text)',
        bear: 'var(--bear)',
        'bear-bg': 'var(--bear-bg)',
        'bear-text': 'var(--bear-text)',
        neutral: 'var(--neutral)',
        'neutral-bg': 'var(--neutral-bg)',
        'neutral-text': 'var(--neutral-text)',
        brand: 'var(--brand)',
        'brand-muted': 'var(--brand-muted)',
        'brand-glow': 'var(--brand-glow)',
        'brand-hover': 'var(--brand-hover)',
        'focus-ring': 'var(--focus-ring)',
      },
    },
  },
  plugins: [],
};
